//next js react component

import React from "react";
import Link from "next/link";

const Index = () => {
  return (
    <div>
      <h1>Home</h1>
      <Link href="/about">
        <span>About</span>
      </Link>
      HOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGE
      HOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGE
      HOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGE
      HOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGE
      HOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGE
      HOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGE
      HOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGEHOMEPAGE
    </div>
  );
};

export default Index;
